name: SensoRRD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: quol/sensorrd
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo apt-get install -y librrd-dev libsensors-dev
    - name: make
      run: make
